version: "3"
services:
 python_service:
   build:
     context: ./
     dockerfile: Dockerfile
   image: workshop1
   container_name: workshop_python_container
   stdin_open: true #  docker attach container_id
   tty: true
   ports:
    - "8000:8000"
   volumes:
    - .:/app
